"""QA issue registry and repair-guide metadata."""
from __future__ import annotations


VALID_MODES = {"user", "developer"}

OWNER_BY_CODE = {
    "MISSING_DOCX": "script_generator.py",
    "MISSING_BUILD_SCRIPT": "script_generator.py",
    "GENERATED_SCRIPT_UNSAFE_UNICODE_DECODE": "script_generator.py / qa_checker.py",
    "MISSING_FORMAT_JSON": "format_extractor.py / md_parser.py",
    "MISSING_CONTENT_JSON": "content_parser.py / md_parser.py",
    "FORMAT_EMPTY": "format_extractor.py / md_parser.py",
    "CONTENT_EMPTY": "content_parser.py / md_parser.py",
    "SOURCE_FORMAT_UNSUPPORTED": "run_pipeline.py / content_parser.py",
    "LEGACY_DOC_UNSUPPORTED": "run_pipeline.py / content_parser.py",
    "SOURCE_TEXTBOX_UNSUPPORTED": "content_parser.py / content_parser_modules/source_audit.py",
    "SOURCE_FOOTNOTE_UNSUPPORTED": "content_parser.py / content_parser_modules/source_audit.py",
    "SOURCE_ENDNOTE_UNSUPPORTED": "content_parser.py / content_parser_modules/source_audit.py",
    "TRACKED_CHANGES_PRESENT": "content_parser.py / content_parser_modules/source_audit.py",
    "COMMENTS_PRESENT": "content_parser.py / content_parser_modules/source_audit.py",
    "CONTENT_CONTROL_UNSUPPORTED": "content_parser.py / content_parser_modules/source_audit.py",
    "SOURCE_EMBEDDED_OBJECT_UNSUPPORTED": "content_parser.py / content_parser_modules/source_audit.py",
    "SOURCE_LANDSCAPE_SECTION_UNSUPPORTED": "content_parser.py / content_parser_modules/source_audit.py / qa_visual.py",
    "CONTENT_IMAGE_FORMAT_UNSUPPORTED": "content_parser.py / content_parser_modules/source_audit.py",
    "COMPLEX_TABLE_UNSUPPORTED": "content_parser.py / content_parser_modules/source_audit.py / script_generator.py",
    "TABLE_MERGE_UNSUPPORTED": "content_parser.py / content_parser_modules/source_audit.py / script_generator.py",
    "STYLE_PROFILE_MISSING": "format_extractor.py / script_generator.py",
    "COVER_NOT_EXTRACTED": "format_extractor.py / script_generator.py",
    "PDF_TEMPLATE_UNSUPPORTED": "format_extractor.py / format_extractor_modules/pdf_template.py",
    "PDF_TEMPLATE_READ_FAILED": "format_extractor.py / format_extractor_modules/pdf_template.py",
    "PDF_TEMPLATE_PROTECTED": "format_extractor.py / format_extractor_modules/pdf_template.py",
    "PDF_TEMPLATE_DEPENDENCY_MISSING": "local environment / Poppler / format_extractor_modules/pdf_template.py",
    "PDF_TEMPLATE_LIMITED_CONFIDENCE": "format_extractor.py / format_extractor_modules/pdf_template.py / template_profiler.py",
    "PDF_TEMPLATE_INSTRUCTION_INCOMPLETE": "format_extractor.py / format_extractor_modules/pdf_template.py / template_profiler.py",
    "PDF_TEMPLATE_VISUAL_APPROXIMATION": "format_extractor.py / format_extractor_modules/pdf_template.py / template_profiler.py",
    "PDF_TEMPLATE_LANDSCAPE_PAGE": "format_extractor.py / format_extractor_modules/pdf_template.py / template_profiler.py",
    "TITLE_MISSING": "content_parser.py / md_parser.py",
    "REFERENCES_MISSING": "content_parser.py / md_parser.py",
    "DOCX_XML_UNREADABLE": "script_generator.py",
    "LATEX_ERROR_TEXT": "latex_omath.py / script_generator.py",
    "LATEX_DELIMITER_TEXT": "content_parser.py / script_generator.py / latex_omath.py",
    "FORMULA_PIPE_ARTIFACT": "latex_omath.py",
    "FORMULA_COUNT_MISMATCH": "content_parser.py / md_parser.py / script_generator.py / latex_omath.py",
    "FORMULA_NOT_NATIVE": "content_parser.py / script_generator.py / latex_omath.py",
    "IMAGE_NOT_RENDERED": "content_parser.py / script_generator.py",
    "IMAGE_COUNT_MISMATCH": "content_parser.py / script_generator.py",
    "CONTENT_IMAGE_MISSING": "md_parser.py / content_parser.py",
    "CONTENT_IMAGE_REMOTE_UNSUPPORTED": "md_parser.py / qa_checker.py",
    "CONTENT_IMAGE_UNREADABLE": "md_parser.py / qa_checker.py",
    "IMAGE_EXTRACT_FAILED": "content_parser.py",
    "NON_BODY_IMAGE_UNSUPPORTED": "content_parser.py / script_generator.py",
    "LOW_RES_IMAGE_FRAGMENT": "content_parser.py / script_generator.py / qa_checker.py",
    "TABLE_COUNT_MISMATCH": "content_parser.py / md_parser.py / script_generator.py",
    "FOOTNOTE_RENDER_COUNT_MISMATCH": "content_parser.py / script_generator.py / qa_checker.py",
    "ENDNOTE_RENDER_COUNT_MISMATCH": "content_parser.py / script_generator.py / qa_checker.py",
    "BUILD_MANIFEST_MISSING": "script_generator.py",
    "DOCX_TEXT_TOO_SHORT": "content_parser.py / md_parser.py / script_generator.py",
    "CONTENT_HEADING_MISSING": "content_parser.py / md_parser.py / script_generator.py",
    "CONTENT_TOC_POLLUTION": "content_parser.py / script_generator.py / qa_checker.py",
    "DUPLICATE_FRONT_MATTER_HEADING": "format_extractor.py / script_generator.py / qa_checker.py",
    "UNFILLED_PLACEHOLDER_TEXT": "content_parser.py / script_generator.py / qa_checker.py",
    "FORMULA_NUMBER_CONFLICT": "content_parser.py / script_generator.py / qa_checker.py",
    "FORMULA_TEXT_FRAGMENTED": "content_parser.py / script_generator.py / latex_omath.py",
    "PLACEHOLDER_TEXT_LEFT": "script_generator.py / qa_checker.py",
    "WORD_FIELD_ERROR": "script_generator.py",
    "TOC_MISSING": "script_generator.py",
    "WORKFLOW_MODE_INVALID": "run_pipeline.py",
    "EXTRACTION_VERIFICATION_FAILED": "format_extractor.py / content_parser.py / md_parser.py / run_pipeline.py",
}
try:
    from qa_checker_modules.repair_guides import REPAIR_GUIDES
except ImportError:  # pragma: no cover - package-style imports
    from .repair_guides import REPAIR_GUIDES

