"""Shared base runtime template fragment for generated build scripts."""
from __future__ import annotations

BASE_RUNTIME = r'''
# -*- coding: utf-8 -*-
"""
build_generated.py — generated by role-driven script_generator.py.
运行: python build_generated.py
"""
import json
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile

sys.dont_write_bytecode = True

from lxml import etree
from docx import Document
from docx.shared import Pt, Cm, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING, WD_TAB_ALIGNMENT, WD_TAB_LEADER
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.enum.style import WD_STYLE_TYPE
from docx.image.image import Image as DocxImage
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from latex_omath import latex_to_omath

DATA = json.loads(__DATA_BLOB__)
BASE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(BASE, __OUT_DOCX__)

doc = Document()
TOC_PAGE_MAP = {}
CAPTION_PAGE_MAP = {}
USE_NATIVE_TOC = False
BUILD_STATS = {}

ALIGN = {
    'LEFT': WD_ALIGN_PARAGRAPH.LEFT,
    'CENTER': WD_ALIGN_PARAGRAPH.CENTER,
    'RIGHT': WD_ALIGN_PARAGRAPH.RIGHT,
    'JUSTIFY': WD_ALIGN_PARAGRAPH.JUSTIFY,
    'DISTRIBUTE': WD_ALIGN_PARAGRAPH.DISTRIBUTE,
    'DEFAULT': WD_ALIGN_PARAGRAPH.LEFT,
}

CJK_FONTS = {'宋体', '黑体', '楷体', '微软雅黑', '仿宋', '华文宋体', '华文中宋'}


def _style_by_name(name, style_type=WD_STYLE_TYPE.PARAGRAPH):
    try:
        return doc.styles[name]
    except KeyError:
        try:
            return doc.styles.add_style(name, style_type)
        except Exception:
            return None


def _set_style_font(style, east_asia='宋体', latin=None, size=12, bold=False, italic=False):
    if style is None:
        return
    latin = latin or ('Times New Roman' if east_asia in CJK_FONTS else east_asia)
    style.font.name = latin
    style.font.size = Pt(float(size))
    style.font.bold = bool(bold)
    style.font.italic = bool(italic)
    rPr = style._element.get_or_add_rPr()
    rFonts = rPr.find(qn('w:rFonts'))
    if rFonts is None:
        rFonts = OxmlElement('w:rFonts')
        rPr.insert(0, rFonts)
    rFonts.set(qn('w:ascii'), latin)
    rFonts.set(qn('w:hAnsi'), latin)
    rFonts.set(qn('w:eastAsia'), east_asia)
    rFonts.set(qn('w:hint'), 'eastAsia')


def _configure_para_style(style, prof, left_indent_cm=0.0):
    if style is None:
        return
    _set_style_font(style, prof.get('font') or '宋体',
                    'Times New Roman' if (prof.get('font') in CJK_FONTS) else (prof.get('font') or 'Times New Roman'),
                    prof.get('size') or 12, prof.get('bold', False), prof.get('italic', False))
    pf = style.paragraph_format
    fixed = prof.get('line_spacing_fixed_pt')
    if fixed:
        pf.line_spacing = Pt(float(fixed))
    elif prof.get('line_spacing_val'):
        pf.line_spacing = float(prof.get('line_spacing_val'))
    pf.space_before = Pt(float(prof.get('space_before_pt') or 0))
    pf.space_after = Pt(float(prof.get('space_after_pt') or 0))
    pf.first_line_indent = Cm(0)
    pf.left_indent = Cm(float(left_indent_cm or 0))
    pf.alignment = ALIGN.get(prof.get('align') or 'LEFT', WD_ALIGN_PARAGRAPH.LEFT)


def configure_global_styles():
    """Lock styles regenerated by Word/WPS, especially TOC 1/2/3."""
    indents = (DATA.get('rules') or {}).get('toc_indents_cm') or [0.0, 0.74, 1.48]
    for style_name, role_name, indent in [
        ('TOC 1', 'toc1', indents[0] if len(indents) > 0 else 0.0),
        ('TOC 2', 'toc2', indents[1] if len(indents) > 1 else 0.74),
        ('TOC 3', 'toc3', indents[2] if len(indents) > 2 else 1.48),
        ('toc 1', 'toc1', indents[0] if len(indents) > 0 else 0.0),
        ('toc 2', 'toc2', indents[1] if len(indents) > 1 else 0.74),
        ('toc 3', 'toc3', indents[2] if len(indents) > 2 else 1.48),
    ]:
        _configure_para_style(_style_by_name(style_name), profile(role_name), indent)
    for style_name, role_name in [('Heading 1', 'h1'), ('Heading 2', 'h2'), ('Heading 3', 'h3')]:
        _configure_para_style(_style_by_name(style_name), profile(role_name), 0.0)
    _configure_para_style(_style_by_name('Normal'), profile('body'), 0.0)


def has_cjk(text):
    return any('\u4e00' <= c <= '\u9fff' for c in str(text or ''))


def ascii_ratio(text):
    text = str(text or '')
    return sum(1 for c in text if c.isascii() and c.isalpha()) / max(len(text), 1)


def set_run_fonts(run, east_asia='宋体', latin=None):
    latin = latin or ('Times New Roman' if east_asia in CJK_FONTS else east_asia)
    run.font.name = latin
    rPr = run._element.get_or_add_rPr()
    rFonts = rPr.find(qn('w:rFonts'))
    if rFonts is None:
        rFonts = OxmlElement('w:rFonts')
        rPr.insert(0, rFonts)
    rFonts.set(qn('w:ascii'), latin)
    rFonts.set(qn('w:hAnsi'), latin)
    rFonts.set(qn('w:eastAsia'), east_asia)
    rFonts.set(qn('w:hint'), 'eastAsia')


def profile(name):
    return DATA['profiles'].get(name) or DATA['profiles']['body']


def apply_paragraph_profile(p, prof, outline_level=None, first_indent_override=None):
    p.alignment = ALIGN.get(prof.get('align') or 'LEFT', WD_ALIGN_PARAGRAPH.LEFT)
    pf = p.paragraph_format
    fixed = prof.get('line_spacing_fixed_pt')
    if fixed:
        pf.line_spacing = Pt(float(fixed))
    elif prof.get('line_spacing_val'):
        pf.line_spacing = float(prof.get('line_spacing_val'))
    if prof.get('space_before_pt') is not None:
        pf.space_before = Pt(float(prof.get('space_before_pt') or 0))
    if prof.get('space_after_pt') is not None:
        pf.space_after = Pt(float(prof.get('space_after_pt') or 0))
    if prof.get('left_indent_cm') is not None:
        pf.left_indent = Cm(float(prof.get('left_indent_cm') or 0))
    if prof.get('right_indent_cm') is not None:
        pf.right_indent = Cm(float(prof.get('right_indent_cm') or 0))
    hanging = prof.get('hanging_indent_cm')
    if hanging:
        pf.first_line_indent = Cm(-float(hanging))
    else:
        indent = first_indent_override if first_indent_override is not None else prof.get('first_indent_cm')
        if indent:
            pf.first_line_indent = Cm(float(indent))
        else:
            pf.first_line_indent = Cm(0)
    if outline_level is not None:
        pPr = p._element.get_or_add_pPr()
        # Give WPS/Word two independent signals for TOC generation:
        # 1) built-in HeadingN style id; 2) explicit outline level.  Direct
        # formatting is applied after style assignment, so the template look is
        # preserved while WPS can still generate a normal directory.
        level_int = max(0, min(int(outline_level), 8))
        pstyle = pPr.find(qn('w:pStyle'))
        if pstyle is None:
            pstyle = OxmlElement('w:pStyle')
            pPr.insert(0, pstyle)
        pstyle.set(qn('w:val'), 'Heading' + str(level_int + 1))
        old = pPr.find(qn('w:outlineLvl'))
        if old is not None:
            pPr.remove(old)
        ol = OxmlElement('w:outlineLvl')
        ol.set(qn('w:val'), str(level_int))
        pPr.append(ol)


def apply_run_profile(run, prof, text='', superscript=False, force_latin=None):
    font = prof.get('font') or '宋体'
    latin = force_latin
    if not latin:
        if font in CJK_FONTS:
            latin = 'Times New Roman'
        else:
            latin = font
    east_asia = font if font in CJK_FONTS else font
    if ascii_ratio(text) > 0.75 and font in CJK_FONTS:
        east_asia = font
        latin = 'Times New Roman'
    set_run_fonts(run, east_asia, latin)
    run.font.size = Pt(float(prof.get('size') or 12))
    run.bold = bool(prof.get('bold', False))
    run.italic = bool(prof.get('italic', False))
    run.font.superscript = bool(superscript)
    run.font.color.rgb = RGBColor(0, 0, 0)


def citation_pattern():
    return re.compile(r'(\[\d+(?:\s*[-,，、]\s*\d+)*\])')


def add_text_runs(p, text, prof, superscript_citations=False):
    text = str(text or '')
    pos = 0
    pat = citation_pattern() if superscript_citations else None
    matches = list(pat.finditer(text)) if pat else []
    if not matches:
        r = p.add_run(text)
        apply_run_profile(r, prof, text)
        return
    for m in matches:
        if m.start() > pos:
            seg = text[pos:m.start()]
            r = p.add_run(seg)
            apply_run_profile(r, prof, seg)
        r = p.add_run(m.group(1))
        apply_run_profile(r, prof, m.group(1), superscript=True)
        pos = m.end()
    if pos < len(text):
        seg = text[pos:]
        r = p.add_run(seg)
        apply_run_profile(r, prof, seg)


def add_text(text, role='body', first_indent=True, outline_level=None, bold_prefix=None):
    prof = profile(role)
    text = clean_text_artifacts(text)
    if not text:
        return None
    p = doc.add_paragraph()
    apply_paragraph_profile(p, prof, outline_level=outline_level, first_indent_override=(prof.get('first_indent_cm') if first_indent else 0))
    superscript = role == 'body'
    if bold_prefix and text.startswith(bold_prefix):
        r1 = p.add_run(bold_prefix)
        p1 = dict(prof); p1['bold'] = True
        apply_run_profile(r1, p1, bold_prefix)
        add_text_runs(p, text[len(bold_prefix):], prof, superscript)
    else:
        add_text_runs(p, text, prof, superscript)
    return p


def normalize_heading_spacing(text):
    t = str(text or '').strip()
    t = re.sub(r'^(第[一二三四五六七八九十百千万\d]+章)\s*(\S)', r'\1 \2', t)
    t = re.sub(r'^(\d+(?:\.\d+)*)(?![.\d])\s*(\S)', r'\1 \2', t)
    return t


def add_heading(text, level):
    level = max(1, min(int(level or 1), 3))
    # 一级标题居中不缩进；二/三级标题按模板首行缩进2字符。
    p = add_text(normalize_heading_spacing(text), role='h' + str(level), first_indent=(level > 1), outline_level=level - 1)
    if p is not None:
        p.paragraph_format.keep_with_next = True
        p.paragraph_format.keep_together = True
    return p


def text_width_cm():
    page = DATA.get('page') or {}
    try:
        return max(4.0, float(page.get('page_w') or 21.0) - float(page.get('ml') or 2.54) - float(page.get('mr') or 2.54))
    except Exception:
        return 15.0


def text_width_inches(scale=1.0):
    return max(1.0, text_width_cm() * float(scale) / 2.54)


def text_height_cm():
    page = DATA.get('page') or {}
    try:
        return max(4.0, float(page.get('page_h') or 29.7) - float(page.get('mt') or 2.54) - float(page.get('mb') or 2.54))
    except Exception:
        return 24.0


def text_height_inches(scale=1.0):
    return max(1.0, text_height_cm() * float(scale) / 2.54)


def role_line_height_pt(role_name):
    prof = profile(role_name)
    if prof.get('line_spacing_fixed_pt'):
        return float(prof.get('line_spacing_fixed_pt') or 0)
    size = float(prof.get('size') or 12)
    return size * float(prof.get('line_spacing_val') or 1.0)


def caption_block_inches(role_name='figure_caption'):
    prof = profile(role_name)
    total_pt = role_line_height_pt(role_name) + float(prof.get('space_before_pt') or 0) + float(prof.get('space_after_pt') or 0)
    return max(0.0, total_pt / 72.0)


def configure_picture_paragraph(p, keep_with_next=True):
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    pf = p.paragraph_format
    pf.line_spacing = 1.0
    pf.space_before = Pt(0)
    pf.space_after = Pt(0)
    pf.keep_with_next = bool(keep_with_next)
    pf.keep_together = True


def picture_pixel_size(path):
    try:
        image = DocxImage.from_file(path)
        return int(getattr(image, 'px_width', 0) or 0), int(getattr(image, 'px_height', 0) or 0), image
    except Exception:
        return 0, 0, None


def picture_looks_like_low_res_text_fragment(path, context=''):
    px_width, px_height, _ = picture_pixel_size(path)
    if px_width <= 0 or px_height <= 0:
        return False
    context = str(context or '')
    context_hint = bool(re.search(
        r'(fragment|shard|broken|label|formula|equation|text|ocr|'
        r'碎片|残片|公式|方程|标签|标注|文字|截图|图表)',
        context,
        re.I,
    ))
    wide_ratio = px_width / max(px_height, 1)
    tall_ratio = px_height / max(px_width, 1)
    if px_width < 160 and px_height < 45 and wide_ratio >= 2.4:
        return True
    if px_height < 80 and wide_ratio >= 4.0:
        return True
    if px_width < 120 and tall_ratio >= 4.0:
        return True
    if context_hint and px_width < 240 and px_height < 120 and max(wide_ratio, tall_ratio) >= 1.8:
        return True
    return False


def fit_picture_dimensions(path, has_caption=True):
    max_width = Inches(text_width_inches(1.0))
    caption_inches = caption_block_inches('figure_caption') if has_caption else 0.0
    max_height = Inches(max(1.0, text_height_inches() - caption_inches))
    try:
        px_width, px_height, image = picture_pixel_size(path)
        if image is None:
            return max_width, None
        # Very small raster images in DOCX sources are usually chart labels,
        # equation glyph fragments, or pasted object shards.  Upscaling them to
        # the full text width creates huge blurry "text pictures" across pages.
        if px_width and px_height and (px_width < 240 or px_height < 80):
            return image.scaled_dimensions()
        width, height = image.scaled_dimensions(width=max_width)
        if height > max_height:
            width, height = image.scaled_dimensions(height=max_height)
        return width, height
    except Exception:
        return max_width, None


def setup_section(sec):
    page = DATA['page']
    page_w = float(page.get('page_w') or 21.0)
    page_h = float(page.get('page_h') or 29.7)
    sec.page_width = Cm(page_w)
    sec.page_height = Cm(page_h)
    sec.top_margin = Cm(float(page.get('mt') or 2.54))
    sec.bottom_margin = Cm(float(page.get('mb') or 2.54))
    sec.left_margin = Cm(float(page.get('ml') or 2.54))
    sec.right_margin = Cm(float(page.get('mr') or 2.54))
    try:
        pg_sz = sec._sectPr.find(qn('w:pgSz'))
        if pg_sz is not None:
            orient_attr = qn('w:orient')
            if page_w > page_h:
                pg_sz.set(orient_attr, 'landscape')
            elif orient_attr in pg_sz.attrib:
                del pg_sz.attrib[orient_attr]
    except Exception:
        pass


def add_page_field(paragraph):
    r = paragraph.add_run()
    begin = OxmlElement('w:fldChar'); begin.set(qn('w:fldCharType'), 'begin')
    instr = OxmlElement('w:instrText'); instr.set(qn('xml:space'), 'preserve'); instr.text = ' PAGE '
    end = OxmlElement('w:fldChar'); end.set(qn('w:fldCharType'), 'end')
    r._element.append(begin); r._element.append(instr); r._element.append(end)
    return r


def set_page_numbering(sec, fmt='decimal', start=1):
    sectPr = sec._sectPr
    pg = sectPr.find(qn('w:pgNumType'))
    if pg is None:
        pg = OxmlElement('w:pgNumType')
        sectPr.append(pg)
    # New sections created by python-docx copy the previous section's
    # w:start.  If this continuation section should not restart numbering,
    # remove the copied attribute instead of leaving another start=1 behind.
    if start is None:
        start_attr = qn('w:start')
        if start_attr in pg.attrib:
            del pg.attrib[start_attr]
    else:
        pg.set(qn('w:start'), str(start))
    pg.set(qn('w:fmt'), fmt)


def apply_header_footer(sec, page_fmt='decimal', start=1):
    hdr = DATA['page'].get('header') or {}
    sec.header.is_linked_to_previous = False
    sec.footer.is_linked_to_previous = False
    hp = sec.header.paragraphs[0]
    hp.text = ''
    hp.alignment = ALIGN.get(hdr.get('align', 'CENTER'), WD_ALIGN_PARAGRAPH.CENTER)
    if hdr.get('text'):
        r = hp.add_run(hdr['text'])
        apply_run_profile(r, {'font': hdr.get('font') or '宋体', 'size': hdr.get('size') or 9, 'bold': hdr.get('bold', False), 'italic': hdr.get('italic', False)}, hdr['text'])
        pPr = hp._element.get_or_add_pPr()
        pBdr = OxmlElement('w:pBdr')
        bottom = OxmlElement('w:bottom')
        bottom.set(qn('w:val'), 'single'); bottom.set(qn('w:sz'), '4'); bottom.set(qn('w:space'), '1'); bottom.set(qn('w:color'), 'auto')
        pBdr.append(bottom); pPr.append(pBdr)
    fp = sec.footer.paragraphs[0]
    fp.text = ''
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = add_page_field(fp)
    apply_run_profile(r, {'font': hdr.get('font') or '宋体', 'size': hdr.get('size') or 9}, '')
    set_page_numbering(sec, page_fmt, start)


def clear_header_footer(sec):
    sec.header.is_linked_to_previous = False
    sec.footer.is_linked_to_previous = False
    for part in (sec.header, sec.footer):
        for p in part.paragraphs:
            p.text = ''


def _paragraph_is_empty_for_cleanup(p):
    if p.text.strip():
        return False
    xml = p._element.xml
    if '<w:drawing' in xml or '<w:pict' in xml or 'oMath' in xml:
        return False
    pPr = p._element.find(qn('w:pPr'))
    if pPr is not None and pPr.find(qn('w:sectPr')) is not None:
        return False
    return True


def remove_trailing_empty_body_paragraphs(limit=12):
    removed = 0
    while len(doc.paragraphs) > 1 and removed < limit and _paragraph_is_empty_for_cleanup(doc.paragraphs[-1]):
        el = doc.paragraphs[-1]._element
        el.getparent().remove(el)
        removed += 1


def add_section_with_header(page_fmt='decimal', start=1):
    remove_trailing_empty_body_paragraphs()
    sec = doc.add_section(WD_SECTION.NEW_PAGE)
    setup_section(sec)
    apply_header_footer(sec, page_fmt, start)
    return sec


def remove_initial_empty_paragraph():
    if len(doc.paragraphs) == 1 and not doc.paragraphs[0].text.strip():
        el = doc.paragraphs[0]._element
        el.getparent().remove(el)


def force_cover_headerless():
    if not doc.sections:
        return
    sec = doc.sections[0]
    sec.different_first_page_header_footer = True
    for part in (sec.header, sec.first_page_header, sec.footer, sec.first_page_footer):
        part.is_linked_to_previous = False
        for p in part.paragraphs:
            p.text = ''
'''
